import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { config } from '../config.js';
import type { ActionStatus, ConsentChannel, ConsentPurpose, ConsentRecord, ExecutionReceipt, UsageEvent, VerifiedAction } from './types.js';

export interface ActionStore {
  createAction(action: VerifiedAction): Promise<VerifiedAction>; getAction(id: string): Promise<VerifiedAction | null>; getActionByKey(businessId: string, key: string): Promise<VerifiedAction | null>; updateAction(id: string, status: ActionStatus, values?: Partial<VerifiedAction>): Promise<void>; claimAction(id: string, approvedBy: string, approvedAt: string): Promise<boolean>;
  addConsent(consent: ConsentRecord): Promise<void>; findConsent(businessId: string, subject: string, purpose: ConsentPurpose, channel: ConsentChannel): Promise<ConsentRecord | null>;
  addReceipt(receipt: ExecutionReceipt): Promise<void>; getReceiptByAction(actionId: string): Promise<ExecutionReceipt | null>; findReceiptByProviderId(providerId: string): Promise<ExecutionReceipt | null>; updateReceipt(id: string, status: ExecutionReceipt['status'], verified: boolean, details: Record<string, unknown>): Promise<void>;
  addUsage(events: UsageEvent[]): Promise<void>; upsertCrmContact(businessId: string, externalKey: string, data: Record<string, unknown>): Promise<string>;
  getIntegration(businessId: string, provider: string): Promise<Record<string, unknown> | null>;
}

export class MemoryActionStore implements ActionStore {
  actions = new Map<string, VerifiedAction>(); consents: ConsentRecord[] = []; receipts = new Map<string, ExecutionReceipt>(); usage: UsageEvent[] = []; contacts = new Map<string, Record<string, unknown>>(); integrations = new Map<string, Record<string, unknown>>();
  async createAction(action: VerifiedAction) { this.actions.set(action.id, structuredClone(action)); return action; }
  async getAction(id: string) { return structuredClone(this.actions.get(id) ?? null); }
  async getActionByKey(businessId: string, key: string) { return structuredClone([...this.actions.values()].find((item) => item.businessId === businessId && item.idempotencyKey === key) ?? null); }
  async updateAction(id: string, status: ActionStatus, values: Partial<VerifiedAction> = {}) { const action = this.actions.get(id); if (!action) throw new Error('Action not found'); this.actions.set(id, { ...action, ...values, status, updatedAt: new Date().toISOString() }); }
  async claimAction(id: string, approvedBy: string, approvedAt: string) { const action = this.actions.get(id); if (!action || action.status !== 'pending_approval') return false; this.actions.set(id, { ...action, status: 'executing', approvedBy, approvedAt, updatedAt: new Date().toISOString() }); return true; }
  async addConsent(consent: ConsentRecord) { this.consents.push(structuredClone(consent)); }
  async findConsent(businessId: string, subject: string, purpose: ConsentPurpose, channel: ConsentChannel) { const latest = [...this.consents].filter((item) => item.businessId === businessId && item.subject === subject && item.purpose === purpose && item.channel === channel).sort((a, b) => (b.revokedAt ?? b.grantedAt).localeCompare(a.revokedAt ?? a.grantedAt))[0]; return structuredClone(latest?.status === 'granted' ? latest : null); }
  async addReceipt(receipt: ExecutionReceipt) { this.receipts.set(receipt.id, structuredClone(receipt)); }
  async getReceiptByAction(actionId: string) { return structuredClone([...this.receipts.values()].find((item) => item.actionId === actionId) ?? null); }
  async findReceiptByProviderId(providerId: string) { return structuredClone([...this.receipts.values()].find((item) => item.providerResourceId === providerId) ?? null); }
  async updateReceipt(id: string, status: ExecutionReceipt['status'], verified: boolean, details: Record<string, unknown>) { const receipt = this.receipts.get(id); if (!receipt) throw new Error('Receipt not found'); this.receipts.set(id, { ...receipt, status, verified, details: { ...receipt.details, ...details }, updatedAt: new Date().toISOString() }); }
  async addUsage(events: UsageEvent[]) { this.usage.push(...structuredClone(events)); }
  async upsertCrmContact(businessId: string, externalKey: string, data: Record<string, unknown>) { const id = `${businessId}:${externalKey}`; this.contacts.set(id, structuredClone(data)); return id; }
  async getIntegration(businessId: string, provider: string) { return structuredClone(this.integrations.get(`${businessId}:${provider}`) ?? null); }
}

export class SupabaseActionStore implements ActionStore {
  constructor(private client: SupabaseClient) {}
  async createAction(action: VerifiedAction) { const { error } = await this.client.from('verified_actions').insert(toAction(action)); if (error) throw error; return action; }
  async getAction(id: string) { const { data, error } = await this.client.from('verified_actions').select('*').eq('id', id).maybeSingle(); if (error) throw error; return data ? fromAction(data) : null; }
  async getActionByKey(businessId: string, key: string) { const { data, error } = await this.client.from('verified_actions').select('*').eq('business_id', businessId).eq('idempotency_key', key).maybeSingle(); if (error) throw error; return data ? fromAction(data) : null; }
  async updateAction(id: string, status: ActionStatus, values: Partial<VerifiedAction> = {}) { const { error } = await this.client.from('verified_actions').update({ status, approved_by: values.approvedBy, approved_at: values.approvedAt, updated_at: new Date().toISOString() }).eq('id', id); if (error) throw error; }
  async claimAction(id: string, approvedBy: string, approvedAt: string) { const { data, error } = await this.client.from('verified_actions').update({ status: 'executing', approved_by: approvedBy, approved_at: approvedAt, updated_at: new Date().toISOString() }).eq('id', id).eq('status', 'pending_approval').select('id').maybeSingle(); if (error) throw error; return Boolean(data); }
  async addConsent(c: ConsentRecord) { const { error } = await this.client.from('consent_records').insert({ id: c.id, business_id: c.businessId, subject: c.subject, purpose: c.purpose, channel: c.channel, status: c.status, source: c.source, evidence: c.evidence, granted_at: c.grantedAt, revoked_at: c.revokedAt }); if (error) throw error; }
  async findConsent(b: string, s: string, p: ConsentPurpose, c: ConsentChannel) { const { data, error } = await this.client.from('consent_records').select('*').eq('business_id', b).eq('subject', s).eq('purpose', p).eq('channel', c).order('granted_at', { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data?.status === 'granted' ? { id: data.id, businessId: data.business_id, subject: data.subject, purpose: data.purpose, channel: data.channel, status: data.status, source: data.source, evidence: data.evidence, grantedAt: data.granted_at, revokedAt: data.revoked_at ?? undefined } : null; }
  async addReceipt(r: ExecutionReceipt) { const { error } = await this.client.from('execution_receipts').insert({ id: r.id, action_id: r.actionId, business_id: r.businessId, provider: r.provider, provider_resource_id: r.providerResourceId, status: r.status, verified: r.verified, details: r.details, created_at: r.createdAt, updated_at: r.updatedAt }); if (error) throw error; }
  async getReceiptByAction(id: string) { const { data, error } = await this.client.from('execution_receipts').select('*').eq('action_id', id).maybeSingle(); if (error) throw error; return data ? fromReceipt(data) : null; }
  async findReceiptByProviderId(id: string) { const { data, error } = await this.client.from('execution_receipts').select('*').eq('provider_resource_id', id).maybeSingle(); if (error) throw error; return data ? fromReceipt(data) : null; }
  async updateReceipt(id: string, status: ExecutionReceipt['status'], verified: boolean, details: Record<string, unknown>) { const receipt = await this.client.from('execution_receipts').select('details').eq('id', id).single(); if (receipt.error) throw receipt.error; const { error } = await this.client.from('execution_receipts').update({ status, verified, details: { ...(receipt.data.details ?? {}), ...details }, updated_at: new Date().toISOString() }).eq('id', id); if (error) throw error; }
  async addUsage(events: UsageEvent[]) { if (!events.length) return; const { error } = await this.client.from('usage_events').insert(events.map((e) => ({ business_id: e.businessId, action_id: e.actionId, metric: e.metric, quantity: e.quantity, estimated_cost_micros: e.estimatedCostMicros, occurred_at: e.occurredAt }))); if (error) throw error; }
  async upsertCrmContact(b: string, key: string, data: Record<string, unknown>) { const { data: row, error } = await this.client.from('crm_contacts').upsert({ business_id: b, external_key: key, data, updated_at: new Date().toISOString() }, { onConflict: 'business_id,external_key' }).select('id').single(); if (error) throw error; return row.id; }
  async getIntegration(b: string, p: string) { const { data, error } = await this.client.from('integration_connections').select('config, credentials_ciphertext').eq('business_id', b).eq('provider', p).eq('status', 'active').maybeSingle(); if (error) throw error; return data ? { ...(data.config ?? {}), credentialsCiphertext: data.credentials_ciphertext } : null; }
}

export function createActionStore(): ActionStore { if (config.SUPABASE_URL && config.SUPABASE_SERVICE_ROLE_KEY) return new SupabaseActionStore(createClient(config.SUPABASE_URL, config.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } })); if (config.NODE_ENV === 'production') throw new Error('Persistent action store required'); return new MemoryActionStore(); }
function toAction(a: VerifiedAction) { return { id: a.id, business_id: a.businessId, kind: a.kind, status: a.status, idempotency_key: a.idempotencyKey, payload: a.payload, consent_id: a.consentId, approved_by: a.approvedBy, approved_at: a.approvedAt, created_at: a.createdAt, updated_at: a.updatedAt }; }
function fromAction(d: Record<string, any>): VerifiedAction { return { id: d.id, businessId: d.business_id, kind: d.kind, status: d.status, idempotencyKey: d.idempotency_key, payload: d.payload, consentId: d.consent_id ?? undefined, approvedBy: d.approved_by ?? undefined, approvedAt: d.approved_at ?? undefined, createdAt: d.created_at, updatedAt: d.updated_at }; }
function fromReceipt(d: Record<string, any>): ExecutionReceipt { return { id: d.id, actionId: d.action_id, businessId: d.business_id, provider: d.provider, providerResourceId: d.provider_resource_id, status: d.status, verified: d.verified, details: d.details, createdAt: d.created_at, updatedAt: d.updated_at }; }
