import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { config, assertGoogleOAuthConfig } from '../config.js';
import { decryptCredentials, encryptCredentials } from '../actions/vault.js';
import { agentIds, type AgentId } from '../agents/types.js';
import type { GoogleOAuthStore } from '../integrations/google-calendar.js';
import { chunks, extractKnowledge } from './parser.js';
import type { KnowledgeStore } from './store.js';
import { supportedDriveMimeTypes, type DriveConnection, type DriveFile } from './types.js';

const driveScope = 'https://www.googleapis.com/auth/drive.file';
const folderMime = 'application/vnd.google-apps.folder';
const templateNames = ['00 — Business Profile', '01 — Hours and Locations', '02 — Products and Services', '03 — Menu and Pricing', '04 — Policies and FAQs', '05 — Promotions and Events', '06 — Team Information', '07 — Brand Voice and Marketing', '08 — Appointments and Operations', '09 — Approved Agent Instructions', '10 — Reports from BusiOS'];

export interface DriveGateway {
  exchange(code: string, verifier: string, redirectUri: string): Promise<{ refreshToken?: string; accessToken: string }>;
  refresh(refreshToken: string): Promise<string>; revoke(refreshToken: string): Promise<void>;
  createFolder(token: string, name: string, parentId?: string): Promise<DriveFile>; file(token: string, id: string): Promise<DriveFile>;
  children(token: string, folderId: string): Promise<DriveFile[]>; content(token: string, file: DriveFile): Promise<Buffer>;
  startToken(token: string): Promise<string>; changes(token: string, pageToken: string): Promise<{ newStartPageToken?: string }>;
  watch(token: string, pageToken: string, channel: { id: string; token: string; address: string; expiration: number }): Promise<{ resourceId: string; expiration?: string }>;
  stop(token: string, channelId: string, resourceId: string): Promise<void>;
}

export class GoogleDriveApi implements DriveGateway {
  async exchange(code: string, verifier: string, redirectUri: string) { assertGoogleOAuthConfig(); const body = new URLSearchParams({ code, code_verifier: verifier, client_id: config.GOOGLE_OAUTH_CLIENT_ID!, client_secret: config.GOOGLE_OAUTH_CLIENT_SECRET!, redirect_uri: redirectUri, grant_type: 'authorization_code' }); const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body }); const value = await json<{ refresh_token?: string; access_token?: string }>(response, 'Drive token exchange'); if (!value.access_token) throw new Error('Google OAuth response missing access token'); return { refreshToken: value.refresh_token, accessToken: value.access_token }; }
  async refresh(refreshToken: string) { assertGoogleOAuthConfig(); const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: config.GOOGLE_OAUTH_CLIENT_ID!, client_secret: config.GOOGLE_OAUTH_CLIENT_SECRET!, refresh_token: refreshToken, grant_type: 'refresh_token' }) }); const value = await json<{ access_token?: string }>(response, 'Drive token refresh'); if (!value.access_token) throw new Error('Google token response missing access token'); return value.access_token; }
  async revoke(refreshToken: string) { const response = await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(refreshToken)}`, { method: 'POST' }); if (!response.ok && response.status !== 400) throw new Error(`Google revoke failed: ${response.status}`); }
  async createFolder(token: string, name: string, parentId?: string) { const response = await fetch('https://www.googleapis.com/drive/v3/files?fields=id,name,mimeType,modifiedTime,parents,webViewLink', { method: 'POST', headers: auth(token, true), body: JSON.stringify({ name, mimeType: folderMime, ...(parentId ? { parents: [parentId] } : {}) }) }); return json<DriveFile>(response, 'Drive folder creation'); }
  async file(token: string, id: string) { const response = await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,modifiedTime,md5Checksum,parents,trashed`, { headers: auth(token) }); return json<DriveFile>(response, 'Drive file lookup'); }
  async children(token: string, folderId: string) { const values: DriveFile[] = []; let pageToken = ''; do { const query = new URLSearchParams({ q: `'${folderId.replace(/'/g, "\\'")}' in parents and trashed=false`, fields: 'nextPageToken,files(id,name,mimeType,modifiedTime,md5Checksum,parents,trashed)', pageSize: '1000', ...(pageToken ? { pageToken } : {}) }); const response = await fetch(`https://www.googleapis.com/drive/v3/files?${query}`, { headers: auth(token) }); const value = await json<{ files?: DriveFile[]; nextPageToken?: string }>(response, 'Drive folder scan'); values.push(...(value.files ?? [])); pageToken = value.nextPageToken ?? ''; } while (pageToken); return values; }
  async content(token: string, file: DriveFile) { let url = `https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`; if (file.mimeType === 'application/vnd.google-apps.document') url = `https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}/export?mimeType=text/plain`; if (file.mimeType === 'application/vnd.google-apps.spreadsheet') url = `https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}/export?mimeType=text/csv`; const response = await fetch(url, { headers: auth(token) }); if (!response.ok) throw new Error(`Drive download failed: ${response.status}`); return Buffer.from(await response.arrayBuffer()); }
  async startToken(token: string) { const response = await fetch('https://www.googleapis.com/drive/v3/changes/startPageToken', { headers: auth(token) }); return (await json<{ startPageToken: string }>(response, 'Drive change token')).startPageToken; }
  async changes(token: string, initialToken: string) { let pageToken = initialToken, newStartPageToken: string | undefined; do { const query = new URLSearchParams({ pageToken, pageSize: '1000', fields: 'nextPageToken,newStartPageToken,changes(fileId,removed,file(id,name,mimeType,modifiedTime,md5Checksum,parents,trashed))' }); const response = await fetch(`https://www.googleapis.com/drive/v3/changes?${query}`, { headers: auth(token) }); const value = await json<{ nextPageToken?: string; newStartPageToken?: string }>(response, 'Drive changes'); pageToken = value.nextPageToken ?? ''; newStartPageToken = value.newStartPageToken ?? newStartPageToken; } while (pageToken); return { newStartPageToken }; }
  async watch(token: string, pageToken: string, channel: { id: string; token: string; address: string; expiration: number }) { const response = await fetch(`https://www.googleapis.com/drive/v3/changes/watch?pageToken=${encodeURIComponent(pageToken)}`, { method: 'POST', headers: auth(token, true), body: JSON.stringify({ id: channel.id, type: 'web_hook', address: channel.address, token: channel.token, expiration: channel.expiration }) }); const value = await json<{ resourceId: string; expiration?: string }>(response, 'Drive notification setup'); return value; }
  async stop(token: string, channelId: string, resourceId: string) { const response = await fetch('https://www.googleapis.com/drive/v3/channels/stop', { method: 'POST', headers: auth(token, true), body: JSON.stringify({ id: channelId, resourceId }) }); if (!response.ok && response.status !== 404) throw new Error(`Drive channel stop failed: ${response.status}`); }
}

export class LiveKnowledgeDriveService {
  constructor(private oauthStore: GoogleOAuthStore, private store: KnowledgeStore, private drive: DriveGateway = new GoogleDriveApi()) {}
  async authorizeUser(accessToken: string, businessId: string) { if (!config.SUPABASE_URL || !config.SUPABASE_SERVICE_ROLE_KEY) throw new Error('Supabase authentication is unavailable'); const client = createClient(config.SUPABASE_URL, config.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } }); const { data, error } = await client.auth.getUser(accessToken); if (error || !data.user) throw new Error('Invalid BusiOS session'); if (!await this.store.isBusinessAdmin(data.user.id, businessId)) throw new Error('Business owner or admin access required'); return data.user.id; }
  async connect(businessId: string, userId: string, businessName: string) { assertGoogleOAuthConfig(); const state = randomBytes(32).toString('base64url'), verifier = randomBytes(48).toString('base64url'); await this.oauthStore.createState({ stateHash: hash(state), businessId, userId, verifierCiphertext: encryptCredentials({ verifier, businessName }), expiresAt: new Date(Date.now() + 10 * 60_000).toISOString() }); const challenge = createHash('sha256').update(verifier).digest('base64url'); const query = new URLSearchParams({ client_id: config.GOOGLE_OAUTH_CLIENT_ID!, redirect_uri: redirectUri(), response_type: 'code', scope: driveScope, access_type: 'offline', prompt: 'consent select_account', include_granted_scopes: 'true', state, code_challenge: challenge, code_challenge_method: 'S256' }); return `https://accounts.google.com/o/oauth2/v2/auth?${query}`; }
  async callback(state: string, code: string) { const saved = await this.oauthStore.consumeState(hash(state)); if (!saved) throw new Error('OAuth state is invalid, expired, or already used'); const values = decryptCredentials<{ verifier: string; businessName: string }>(saved.verifierCiphertext); const tokens = await this.drive.exchange(code, values.verifier, redirectUri()); if (!tokens.refreshToken) throw new Error('Google did not return a refresh token; reconnect and grant consent'); const root = await this.drive.createFolder(tokens.accessToken, `BusiOS — ${values.businessName} — ${saved.businessId.slice(0, 6)}`); for (const name of templateNames) await this.drive.createFolder(tokens.accessToken, name, root.id); const connection: DriveConnection = { businessId: saved.businessId, folderId: root.id, folderName: root.name, credentialsCiphertext: encryptCredentials({ refreshToken: tokens.refreshToken }), status: 'active' }; await this.store.saveConnection(connection); await this.sync(saved.businessId); await this.renew(connection); return { businessId: saved.businessId, folderId: root.id, folderName: root.name, folderUrl: `https://drive.google.com/drive/folders/${root.id}` }; }
  async selectFolder(businessId: string, folderId: string) { const connection = await this.requiredConnection(businessId); const token = await this.access(connection), folder = await this.drive.file(token, folderId); if (folder.mimeType !== folderMime || folder.trashed) throw new Error('The selected Google Drive item is not an active folder'); connection.folderId = folder.id; connection.folderName = folder.name; connection.lastError = undefined; await this.store.saveConnection(connection); return this.sync(businessId); }
  async pickerToken(businessId: string) { const connection = await this.requiredConnection(businessId); return { accessToken: await this.access(connection), appId: config.GOOGLE_DRIVE_APP_ID, apiKey: config.GOOGLE_PICKER_API_KEY, scope: driveScope } as const; }
  async sync(businessId: string) { const connection = await this.requiredConnection(businessId); try { const token = await this.access(connection), files = await this.walk(token, connection.folderId), seen = new Set<string>(), existing = await this.store.documents(businessId); for (const file of files) { seen.add(file.id); if (!supportedDriveMimeTypes.includes(file.mimeType as any)) { await this.store.saveDocument({ businessId, fileId: file.id, name: file.name, mimeType: file.mimeType, modifiedTime: file.modifiedTime, checksum: file.md5Checksum ?? file.modifiedTime, version: 1, status: 'unsupported', warning: 'Unsupported file type', allowedAgents: [...agentIds], sourceUrl: source(file.id), content: '' }, []); continue; } const body = await this.drive.content(token, file), parsed = await extractKnowledge(normalizeMime(file.mimeType), body), allowedAgents = policy(file.name); await this.store.saveDocument({ businessId, fileId: file.id, name: file.name, mimeType: file.mimeType, modifiedTime: file.modifiedTime, checksum: parsed.checksum, version: 1, status: parsed.warning ? 'quarantined' : 'indexed', warning: parsed.warning, allowedAgents, sourceUrl: source(file.id), content: parsed.text }, parsed.warning ? [] : chunks(parsed.text)); } for (const document of existing) { const fileId = String(document.fileId ?? (document as Record<string, unknown>).source_file_id ?? ''); if (fileId && !seen.has(fileId)) await this.store.deleteDocument(businessId, fileId); } connection.changeToken = connection.changeToken ?? await this.drive.startToken(token); connection.lastSyncedAt = new Date().toISOString(); connection.lastError = undefined; connection.status = 'active'; await this.store.saveConnection(connection); return { synced: seen.size, lastSyncedAt: connection.lastSyncedAt }; } catch (error) { connection.status = 'error'; connection.lastError = error instanceof Error ? error.message : 'Drive sync failed'; await this.store.saveConnection(connection); throw error; } }
  async notification(channelId: string, channelToken: string) { const connection = await this.store.connectionForChannel(channelId); if (!connection || !connection.channelTokenHash || hash(channelToken) !== connection.channelTokenHash) throw new Error('Invalid Drive notification channel'); const token = await this.access(connection); if (connection.changeToken) { const changes = await this.drive.changes(token, connection.changeToken); connection.changeToken = changes.newStartPageToken ?? connection.changeToken; await this.store.saveConnection(connection); } await this.sync(connection.businessId); if (connection.channelExpiresAt && Date.parse(connection.channelExpiresAt) < Date.now() + 24 * 60 * 60_000) await this.renew(connection); }
  async renewExpiring() { const values = await this.store.activeConnections(); let renewed = 0; for (const value of values) if (!value.channelExpiresAt || Date.parse(value.channelExpiresAt) < Date.now() + 24 * 60 * 60_000) { await this.renew(value); renewed++; } return { renewed }; }
  async renew(connection: DriveConnection) { if (!config.PUBLIC_BASE_URL) throw new Error('PUBLIC_BASE_URL is required'); const accessToken = await this.access(connection), pageToken = connection.changeToken ?? await this.drive.startToken(accessToken), id = randomUUID(), channelToken = randomBytes(32).toString('base64url'), expiration = Date.now() + 6 * 24 * 60 * 60_000, previous = connection.channelId && connection.channelResourceId ? { id: connection.channelId, resourceId: connection.channelResourceId } : undefined; const watched = await this.drive.watch(accessToken, pageToken, { id, token: channelToken, address: `${config.PUBLIC_BASE_URL.replace(/\/$/, '')}/webhooks/google/drive`, expiration }); connection.changeToken = pageToken; connection.channelId = id; connection.channelResourceId = watched.resourceId; connection.channelTokenHash = hash(channelToken); connection.channelExpiresAt = new Date(Number(watched.expiration ?? expiration)).toISOString(); await this.store.saveConnection(connection); if (previous) await this.drive.stop(accessToken, previous.id, previous.resourceId); }
  async status(businessId: string) { const value = await this.store.connection(businessId); return value ? { connected: value.status !== 'disconnected', folderId: value.folderId, folderName: value.folderName, folderUrl: sourceFolder(value.folderId), status: value.status, lastSyncedAt: value.lastSyncedAt, lastError: value.lastError, channelExpiresAt: value.channelExpiresAt, documents: await this.store.documents(businessId) } : { connected: false, documents: [] }; }
  async retrieve(businessId: string, agent: AgentId, query: string, limit = 5) { return this.store.retrieve(businessId, agent, query, Math.min(Math.max(limit, 1), 10)); }
  async disconnect(businessId: string) { const value = await this.store.connection(businessId); if (!value) return { disconnected: true }; const { refreshToken } = decryptCredentials<{ refreshToken: string }>(value.credentialsCiphertext), token = await this.drive.refresh(refreshToken); if (value.channelId && value.channelResourceId) await this.drive.stop(token, value.channelId, value.channelResourceId); await this.drive.revoke(refreshToken); value.status = 'disconnected'; value.credentialsCiphertext = encryptCredentials({ revoked: true }); value.channelId = undefined; value.channelResourceId = undefined; value.channelTokenHash = undefined; await this.store.saveConnection(value); return { disconnected: true }; }
  private async requiredConnection(id: string) { const value = await this.store.connection(id); if (!value || value.status === 'disconnected') throw new Error('Google Drive is not connected'); return value; }
  private async access(value: DriveConnection) { const { refreshToken } = decryptCredentials<{ refreshToken: string }>(value.credentialsCiphertext); if (!refreshToken) throw new Error('Google Drive authorization has been revoked'); return this.drive.refresh(refreshToken); }
  private async walk(token: string, root: string) { const files: DriveFile[] = [], queue = [root], visited = new Set<string>(); while (queue.length) { const folder = queue.shift()!; if (visited.has(folder)) continue; visited.add(folder); for (const item of await this.drive.children(token, folder)) { if (item.mimeType === folderMime) queue.push(item.id); else files.push(item); } if (files.length > 2000) throw new Error('Knowledge folder exceeds the 2,000 file limit'); } return files; }
}

function auth(token: string, jsonBody = false) { return { authorization: `Bearer ${token}`, ...(jsonBody ? { 'content-type': 'application/json' } : {}) }; }
async function json<T>(response: Response, label: string) { if (!response.ok) throw new Error(`${label} failed: ${response.status}`); return response.json() as Promise<T>; }
function redirectUri() { if (!config.PUBLIC_BASE_URL) throw new Error('PUBLIC_BASE_URL is required'); return `${config.PUBLIC_BASE_URL.replace(/\/$/, '')}/integrations/google/drive/callback`; }
function hash(value: string) { return createHash('sha256').update(value).digest('hex'); }
function source(id: string) { return `https://drive.google.com/open?id=${encodeURIComponent(id)}`; }
function sourceFolder(id: string) { return `https://drive.google.com/drive/folders/${encodeURIComponent(id)}`; }
function normalizeMime(mime: string) { if (mime === 'application/vnd.google-apps.document') return 'text/plain'; if (mime === 'application/vnd.google-apps.spreadsheet') return 'text/csv'; return mime; }
function policy(name: string): AgentId[] { const value = name.toLowerCase(); if (/finance|invoice|expense|cash|budget/.test(value)) return ['DIEGO', 'LOLA']; if (/staff|employee|team/.test(value)) return ['DIEGO', 'ENRIQUE']; if (/brand|marketing|promotion/.test(value)) return ['DIEGO', 'MIGUEL', 'JULIO', 'MARIA']; if (/lead|sales|customer/.test(value)) return ['DIEGO', 'ZULMA', 'MARISOL', 'MARIA']; return [...agentIds]; }
